//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COGERTI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("AssociacaoRecursos")]
    public partial class AssociacaoRecurso
    {
        public int Id { get; set; }

        [Display(Name = "Matrícula")]
        [Required]
        public int FuncionarioUPI { get; set; }

        [Display(Name = "ID do Recurso")]
        [Required]
        public int RecursoId { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name = "Data da Associação")]
        public System.DateTime DataAssociacao { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name = "Data da Liberação")]
        public Nullable<System.DateTime> DataLiberacao { get; set; }

        [Display(Name = "Motivo da Liberação")]
        public string MotivoLiberacao { get; set; }

        [Display(Name = "Termo de Responsabilidade")]
        public string TermoResponsabilidade { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
        public virtual Recurso Recurso { get; set; }
    }
}
