//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace COGERTI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Computadores")]
    public partial class Computador : Equipamento
    {
        [Display(Name = "Tipo Computador")]
        public int TipoComputadorId { get; set; }
    
        public virtual TipoComputador TipoComputador { get; set; }
    }
}
