//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace COGERTI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Equipamentos")]
    public abstract partial class Equipamento : Recurso
    {
        [Display(Name = "Serial No")]
        public string SerialNo { get; set; }
        [Display(Name = "Patrimônio")]
        [MaxLength(5)]
        public String Patrimonio { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name = "Data da Fabricação")]
        public Nullable<System.DateTime> DataFabricacao { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        [Display(Name = "Propriedade")]
        public int PropriedadeId { get; set; }
        [Display(Name = "Status do Equipamento")]
        public int StatusEquipamentoId { get; set; }
    
        public virtual StatusEquipamento StatusEquipamento { get; set; }
        public virtual PropriedadeEquipamento Propriedade { get; set; }
    }
}
