//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace COGERTI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("LinhasMoveis")]
    public partial class LinhaMovel : Recurso
    {
        [Display(Name = "Linha No")]
        public string LinhaNo { get; set; }
        [Display(Name = "ID do Chip")]
        public string ChipId { get; set; }
        [Display(Name = "Código DDD")]
        public int CodigoDddId { get; set; }
        [Display(Name = "Tipo da Linha")]
        public int TipoLinhaId { get; set; }
        [Display(Name = "Plano Celular")]
        public int TipoPlanoMovelId { get; set; }
    
        public virtual CodigoDdd CodigoDdd { get; set; }
        public virtual TipoLinha TipoLinha { get; set; }
        public virtual TipoPlanoMovel TipoPlanoMovel { get; set; }
    }
}
